server:
    port: 9090
spring:
  redis:
      host: 127.0.0.1
      database: 0
      port: 6379
      password: Asters@123456
      jedis:
          pool:
              max-idle: 8
              max-wait: -1ms
              min-idle: 0
              max-active: 8
      timeout: 10000ms
wechat:
    cp:
        corpId: ww92480eb625f6cf0f
        projectUrl: http://wx.asters.cn/
        userInfoUrl: ${wechat.cp.projectUrl}/wechat/userInfo
        appConfigs:
            - agentId: 1000019
              secret: 54eXGi_TJSGERoixAZ7PqqFOJlO3Qq_B-FMg-lK20Iw
              token:
              aesKey:
            - agentId: 1000022
              secret: Ws-jHbIcqSJ43Cgsc8gOidnVvWoF9_RAlE24Ew9Jrfo
              token:
              aesKey:


