server:
    port: 9090
spring:
  redis:
      host: 127.0.0.1
      database: 0
      port: 6379
      password: Asters@123456
      jedis:
          pool:
              max-idle: 8
              max-wait: -1ms
              min-idle: 0
              max-active: 8
      timeout: 10000ms
wechat:
    cp:
        corpId: ww92480eb625f6cf0f
        projectUrl: http://devwx.asters.cn/
        userInfoUrl: ${wechat.cp.projectUrl}/wechat/userInfo
        appConfigs:
            - agentId: 1000016
              secret: V8yqbZmMYCMza1BPE8LUyGv5iG_3wxi5JfBM1zpANZQ
              token:
              aesKey:
            - agentId: 1000023
              secret: aN2CDdLrrGeVaqWRUl8aYeQuGUUm5dL5S6bcpO0-h40
              token:
              aesKey:
